### ISSUE TITLE
Invalid get index 'motion_velocity' (on base: 'CharacterBody3D ()').

### ISSUE THREAD

**Issue by CloudyChris** [emirthab/third-person-controller#4]
![Screenshot from 2023-01-29 14-53-33](https://user-images.githubusercontent.com/8339678/215327503-62ad03be-2d3a-4817-a0cb-ea4038059a22.png)

I am a noob so if I'm doing something wrong... please tell me.
I am rather confused as to this behavior and it happened with some of my stuff too, forcing me to use "has_node()" and "get_node()" instead of onready vars... But there is no "has_property" afaik...

**Comment by realgdman** [comment]
@CloudyChris Godot 4 in active beta development.
`motion_velocity` needs to be renamed just `velocity`. 
But there are more changes needed for this addon. Something wrong with fall and strafe animations. This addon not working with current beta out of the box.

**Comment by CloudyChris** [comment]
I got used to Godot 4 by now. This engine really needs more dum-dum-proof documentation, because I'm not smart enough...
I'll mark this as closed since it was my misunderstanding rather than an actual issue
